---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
    - name: Get all resource group in subscription
      azure_rm_resourcegroup_facts:
      register: group_array
    - debug:
        var: group_array
